### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by go-dockly** [pehringer/simd#1]
Absolutely, fanning out about your project !!!
Unfortunately, I am on a mac chip :(
If I only had the time to tinker around tho this might be useful resource:

https://github.com/alivanz/go-simd

**Comment by go-dockly** [comment]
### other useful implementations
> https://github.com/minio/highwayhash
> https://github.com/minio/sha256-simd
> https://github.com/minio/simdjson-go
> https://github.com/minio/c2goasm
### assembly goodies
> [Plan9 assembly reference](https://www.quasilyte.dev/blog/post/go-asm-complementary-reference/)
> [ARM64 Instruction set](https://dougallj.github.io/asil/)
> [ARM64 Go support](https://pkg.go.dev/cmd/internal/obj/arm64)
> [Go ARM64 test data](https://github.com/golang/go/blob/master/src/cmd/asm/internal/asm/testdata/arm64enc.s)
> [AVX Instruction set](https://gist.github.com/alexcrichton/3281adb58af7f465cebee49759ae3164)
> [AVX 512 Go support](https://go.dev/wiki/AVX512)
> [Go AVX512 test data](https://github.com/golang/go/tree/master/src/cmd/asm/internal/asm/testdata/avx512enc)
>

**Comment by pehringer** [comment]
Wow tons of great resources here, thank you go-dockly! I will work on adding ARM64 support. I need to get some sort of VM setup for development on my x86_64 machine.

**Comment by go-dockly** [comment]
Kuddos to you man! Have a feel you'll go far. 
Happy to help out where I can with the arm port.
Nice to meet you
